### ISSUE TITLE
IndexError when you get an empty buffer

### ISSUE THREAD

**Issue by astraw38** [fgimian/paramiko-expect#11]
With an SSH session active, reboot or disable networking on the target machine (to close the remote end of the SSH session). Then, try to use paramiko-expect to scan through the shell. I would expect a socket.timeout, but instead you get an IndexError.

This is because the buffer is empty (on retrieval from remote connection), then you try to scan through the current output for the given regex strings, then try to directly access a 'found_pattern' that isn't actually found. 

This could by solved by either converting the While loop to a While: Else (for when the buffer breaks out of the loop), or checking that there is actually a found pattern.

**Comment by fgimian** [comment]
I cannot reproduce this behaviour, I always get a timeout.

Can you please supply example code and the output you receive when running it?

Thanks
Fotis

**Comment by fgimian** [comment]
Hi Ashley, I'll close this issue for now as I haven't heard back from you, but if you do encounter the issue again and can provide more information on reproducing it, I'll happily re-open this.

Thanks
Fotis

**Comment by astraw38** [comment]
Sorry for the long delay, I'll try to get a simple reproduction. Out of curiosity, how did you try to reproduce on your end? It worked properly for me on a regular reboot, but on a hard reset it does not (I'm guessing that's the difference between the remote connection being closed by the OS on a reboot and it just no longer responding).

**Comment by astraw38** [comment]
Ok, verified with a quick test:


```
In [5]: sshclient.set_missing_host_key_policy(paramiko.AutoAddPolicy())

In [6]: sshclient.connect(<removed>, username="root", password=<removed>)

In [7]: expect = SSHClientInteraction(sshclient)

In [8]: expect.expect('deadbeef', timeout=300)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-81c24982fc89> in <module>()
----> 1 expect.expect('deadbeef', timeout=300)

/usr/local/lib/python2.7/site-packages/paramikoe.pyc in expect(self, re_strings,
    164             self.current_output_clean = (
    165                 re.sub(
--> 166                     found_pattern[0][1] + '$', '', self.current_output_c
    167                 )
    168             )

IndexError: list index out of range

In [9]:
```

This was accomplished by running `netstat -tnpa` on the host, then `kill -9 <PID>`, where the PID was the SSHD process associated with the connection between the two machines.

**Comment by fgimian** [comment]
Thanks so much for the information @astraw38, I'll attempt to reproduce this shortly and develop a fix :smile:

**Comment by fruch** [comment]
6b1bad9 fixes this issue, now on the next command you'll get `OSError: Socket is closed`
