### ISSUE TITLE
install paramikoe failed

### ISSUE THREAD

**Issue by xiong72** [fgimian/paramiko-expect#12]
try to install paramiko expect failed with error message, please help
C:\Python34\Scripts>pip install git+https://github.com/fgimian/paramiko-expect.g
it
Collecting git+https://github.com/fgimian/paramiko-expect.git
  Cloning https://github.com/fgimian/paramiko-expect.git to c:\users\xjing\appda
ta\local\temp\pip-xw69qh3c-build
fatal: unable to access 'https://github.com/fgimian/paramiko-expect.git/': Faile
d to connect to github.com port 443: Timed out

**Comment by fgimian** [comment]
Hi, my installation gets much further than yours, the command I used was:

```bash
pip install git+https://github.com/fgimian/paramiko-expect.git
```

Partial output below:

```
C:\Development>virtualenv test-paramikoe
New python executable in C:\Development\test-paramikoe\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Development>.\test-paramikoe\Scripts\activate.bat

(test-paramikoe) C:\Development>pip install git+https://github.com/fgimian/paramiko-expect.git
Collecting git+https://github.com/fgimian/paramiko-expect.git
  Cloning https://github.com/fgimian/paramiko-expect.git to c:\users\d235183\appdata\local\temp\pip-hktbf2-build
Collecting paramiko>=1.10.1 (from paramiko-expect==0.2)
  Using cached paramiko-1.16.0-py2.py3-none-any.whl
Collecting ecdsa>=0.11 (from paramiko>=1.10.1->paramiko-expect==0.2)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting pycrypto!=2.4,>=2.1 (from paramiko>=1.10.1->paramiko-expect==0.2)
  Using cached pycrypto-2.6.1.tar.gz
Building wheels for collected packages: pycrypto
  Running setup.py bdist_wheel for pycrypto ... error
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
Installing collected packages: ecdsa, pycrypto, paramiko, paramiko-expect
  Running setup.py install for pycrypto ... canceled
...
```

I think there's something wrong on your system there.

Further to this, I never really intended to and don't have future plans to support Windows for this library so I'll be closing this issue for now.

Kindest Regards
Fotis
