### ISSUE TITLE
Upload to PyPI?

### ISSUE THREAD

**Issue by martinroos1** [fgimian/paramiko-expect#15]
This is a very useful package, but I don't seem to be able to find it on [PyPI](https://pypi.python.org/pypi). Would it be possible to have the package uploaded to make installation of it easier?

**Comment by pjtait** [comment]
+1

**Comment by fruch** [comment]
+1

**Comment by sho-suzuki** [comment]
+1

**Comment by trigunam** [comment]
+1

**Comment by fruch** [comment]
@fgimian you need help with this ? maybe connecting to travis or something like that would help ? (also to test PR). if we'll have your blessing we might be able to help.

**Comment by fgimian** [comment]
Hey there everyone, thanks so much for your interest in this project.

I am rarely developing open source in my own time these days, hence why I have been very unresponsive here, apologies.

I'd be happy to allow a new maintainer to take over this project along with the few issues that are open including this one.

@fruch if you're interested mate, please let me know :smile: 

Cheers
Fotis

**Comment by fruch** [comment]
@fgimian challenge accepted. I'll open an account in pypi and in travis CI, I'll put a pull request for needed changes when ready.

**Comment by fruch** [comment]
@fgimian 
see 
https://travis-ci.org/fruch/paramiko-expect
with tests and coverage (45% for now)

**Comment by fgimian** [comment]
Thanks @fruch, will check this out asap :smile:

**Comment by fgimian** [comment]
Great job @fruch, I'm happy to provide you committer rights and transition the project to you within the next week or two once you've settled in.  How does that sound mate?

**Comment by fruch** [comment]
I'm ready when you are :)

give me a ping once you gave me permission I'll take from there.

if there are more things you want to talk about leave me email , israel.fruchter@gmail.com

**Comment by fgimian** [comment]
All done @fruch :smile:  Please let me know if it all works for you.

Cheers
Fotis

**Comment by fruch** [comment]
I think I'll need admin rights, in order to commit (or approve PRs)
Also for Travis CI, I might need you to sync your github account for it to work.

**Comment by fgimian** [comment]
@fruch let me take a look buddy, sorry about that 😄

**Comment by fgimian** [comment]
@fruch I've actually sent you a request to become a collaborator but it says that you haven't accepted it.  This should give you full access to this repository.

Regarding Travis CI, I've enabled the repo via my username for you 😄

**Comment by fruch** [comment]
@fgimian oops, I'm used to GitHub Enterprise, where you just add the user. no accepting on his part (I guess cause we all in the same group)

And we could get down to business...

**Comment by fruch** [comment]
it's now up in pypi 
https://pypi.python.org/pypi/paramiko-expect/0.2.5
enjoy...

**Comment by fgimian** [comment]
Thanks @fruch, great job!

**Comment by fgimian** [comment]
@fruch I can see you've been busy doing a great job cleaning up issues.  I'm more than happy to transfer the repo to your account now if you like.  You are also welcome to change the maintainer name to your own and simply list me somewhere in the README as a courtesy.

What do you think mate?
Fotis

**Comment by fruch** [comment]
@fgimian I'm honored, but lets keep it like that for now. I think you can take the [MAINTINER NEEDED] sign out of the front door.

I might reconsider if i'l be on a job hunt again :) 
meanwhile I'm stay as a not so "silent" partner.

**Comment by fgimian** [comment]
@fruch no worries mate
