### ISSUE TITLE
Cannot install package paramiko_expect into server

### ISSUE THREAD

**Issue by steventran1983** [fgimian/paramiko-expect#40]
Hello everyone, 
I want to install package paramiko_expect to Unix server by pip . 
For some reason , maybe firewall prevent I could not. 
Is there any way to install paramiko_expect manually by file or any way that do not need yo use pip .

**Comment by fgimian** [comment]
This is a more general pip question as opposed to a project specific one, you really should reserve questions like this for stackoverflow.

You can download both egg and  wheel packages on this page https://pypi.python.org/pypi/paramiko-expect/0.2.8 and then simply `pip install <filename>` them.

Cheers
Fotis
