### ISSUE TITLE
expect() method assumes '$' as the bash prompt suffix, fails for other flavours of linux such fc19. It would be better to have this as an argument to the method

### ISSUE THREAD

**Issue by nisar009** [fgimian/paramiko-expect#45]

**Comment by fgimian** [comment]
The `$` is a regular expression end of line, not a literal.

**Comment by nisar009** [comment]
But wouldn't the regex fail to match if the prompt ends with characters other than $?

**Comment by fgimian** [comment]
> But wouldn't the regex fail to match if the prompt ends with characters other than $?

Nope, because the `$` indicates the **end of line**, not a literal `$`.
