### ISSUE TITLE
Hardcoded $ in re_string

### ISSUE THREAD

**Issue by rymka1989** [fgimian/paramiko-expect#47]
Hi!
I'm running Centos and there is no $ symbol in prompt, it has # instead.
In other operations, e.g. changing user password, there are no symbols ($, #) at all.

So, may be it should better not to include such symbols in re_strings in expect method?

After I've removed + '$' everything works fine.

**Comment by rymka1989** [comment]
> Hi!
> I'm running Centos and there is no $ symbol in prompt, it has # instead.
> In other operations, e.g. changing user password, there are no symbols ($, #) at all.
> 
> So, may be it should better not to include such symbols in re_strings in expect method?
> 
> After I've removed + '$' everything works fine.

I realized something :)
If i login with root, i have # at the end of the prompt, if i login with another user, i have $.
But previous comment, i think, is still actual (we don't need hardcoded $)

**Comment by y-me-y** [comment]
@rymka1989 - that is actually regex for matching the end of line and before a return if a multiline input. There isn’t a literal match for the string $.

**Comment by fgimian** [comment]
As @y-me-y explained, this is a regular expression, the `$` is the end of line, not a literal.  More likely there's something happening on your prompt before the end of line is matched.
