### ISSUE TITLE
add term support to SSHClientInteraction , to pass onto invoke_shell

### ISSUE THREAD

**Issue by sar772004** [fgimian/paramiko-expect#89]
In our use case, we want a dumb terminal for the cli we are connecting too and not the vt100 which is the parmiko default

**Comment by sar772004** [comment]
https://github.com/fgimian/paramiko-expect/pull/90

**Comment by fruch** [comment]
Closed by #90

**Comment by sar772004** [comment]
@fruch can you pls see why the deploy of 0.3.5 is skipped ? would appreciate if this can get in soon.

Thanks

**Comment by fruch** [comment]
> @fruch can you pls see why the deploy of 0.3.5 is skipped ? would appreciate if this can get in soon.
> 
> Thanks

Release is still a manual process,

I might take me a few days to get to it.

**Comment by sar772004** [comment]
@fruch  Any body else can help release, sort of blocking me ?

**Comment by sar772004** [comment]
Gentle reminder.. Thanks,
