### ISSUE TITLE
Moving this repo into its own organisation

### ISSUE THREAD

**Issue by fgimian** [fgimian/paramiko-expect#96]
Hey @fruch, thanks so much for helping with support of this library.

I haven't had a need for this since I wrote it personally and these days I don't really work on any new Python projects (everything is Go, Rust or C#).

How would you feel about me moving this repo into a paramiko-expect organisation and giving you full rights. I can also retain rights until we can find at least one more maintainer to help you out.

Cheers
Fotis

**Comment by fruch** [comment]
I think it's a good idea 

I myself am not using this package anymore for years, so looking for a maintainer that uses it, is the way to go.

I'm still working a lot on python projects, so issues with packing/CI/testing I can help with, but I don't have time to actively work on issues or enhancements.

Also now part of my day job, I'm actively a maintainer of other open source projects that keep me quite busy.

Thanks again @fgimian, it was a very welcoming experience, as the first project I was a maintainer in

**Comment by fgimian** [comment]
> I think it's a good idea
> 
> I myself am not using this package anymore for years, so looking for a maintainer that uses it, is the way to go.
> 
> I'm still working a lot on python projects, so issues with packing/CI/testing I can help with, but I don't have time to actively work on issues or enhancements.
> 
> Also now part of my day job, I'm actively a maintainer of other open source projects that keep me quite busy.
> 
> Thanks again @fgimian, it was a very welcoming experience, as the first project I was a maintainer in

Thanks mate, it seems that you need a public contact email address to create an organization on GitHub so I may hold off for now. Instead I'll pin an issue asking for maintainers to take over.

**Comment by adityarishu** [comment]
Hi @fgimian

I am actively using this library from past 6 years now. I would like to be the primary maintainer of the library.

Thank You!
Aditya

**Comment by fgimian** [comment]
I have decided to archive this repo so this issue is no longer relevant.
