### ISSUE TITLE
Maintainers required

### ISSUE THREAD

**Issue by fgimian** [fgimian/paramiko-expect#97]
Hi there, I originally created this project a very very long time ago while working on some Cisco device automation while working in ops. Personally I have not used this library in over 10 years. @fruch who has been kindly hepling out is also no longer using the library himself.

The library continues to gain stars so it may be useful to some people out there.

If you are interested in becoming the primary maintainer of the library, please let me know. If all else fails and @fruch has no time to work on the project, I'll consider archiving it in the coming year. Forks are welcome at any time of course.

Cheers
Fotis

**Comment by fgimian** [comment]
Thsnks guys, I'll get to this over the next few days ❤️

**Comment by fgimian** [comment]
I apologise for being so late to action this but I've added both @adityarishu and @sriramkannan95 as collaborators.

@adityarishu If you are happy to become the primary maintainer, I'd like to move over the repository to your GitHub. @fruch can provide you PyPI rights to publish new releases as he took over ownership of the package on PyPi.

Cheers
Fotis

**Comment by adityarishu** [comment]
Hi @fgimian 

I would like to be the primary maintainer. Please consider moving the repository to my GitHub. 

Thank You!
Aditya

**Comment by fgimian** [comment]
> Hi @fgimian 
> 
> I would like to be the primary maintainer. Please consider moving the repository to my GitHub. 
> 
> Thank You!
> Aditya 

Thanks so much mate. 😊

I think it may be best to take our time with the transition to give you time to get comfortable. Once you have started contributing commits, responding to issues and are settled in, I'll transfer the repo over.

Cheers
Fotis

**Comment by fgimian** [comment]
If anyone has an email address we can use for the project, it would be ideal to move this into an organisation.

Cheers
Fotis

**Comment by fgimian** [comment]
@adityarishu @sriramkannan95 I notice you haven't been actively working on this library since our discussion, are you still interested in maintaining it? No worries at all if not, I totally understand how hard it is to find free time.

I will open this up to the community again, if anyone else is interested in taking over this library, please let me know.

Failing this, I will likely archive the repository in the coming weeks and welcome forks instead.

Cheers
Fotis

**Comment by fgimian** [comment]
I have decided to go ahead with the archival of this repository. If you wish to continue development of paramiko-expect, please feel free to fork the project. 😄
